ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "ramSlot1" TEXT;
ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "ramSlot2" TEXT;
ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "gpu" TEXT;
ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "osType" TEXT;
ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "macosVersion" TEXT;
ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "snComputer" TEXT;
